# R 과 Python 8주차 - 제2강

## Python 유용한 패키지들

다음 셀은, 이후의 셀에서, 각 셀에서 여러 개의 출력를
표시하도록 하는 옵션 설정 변경임

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

### numpy / pandas

In [2]:
import numpy as np
import pandas as pd

/var/folders/y2/kl2gq1515fz08_5f53vfhm_m0000gn/T/ipykernel_69392/1662815981.py:2: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas as pd


### numpy

In [4]:
xa = np.arange(1,12+1)
xr = np.random.choice(xa,9)
xa
xr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

array([ 1,  6, 10,  3,  3,  4, 11,  6,  8])

xa 는 1부터 12까지의 수열,

xr 은 xa 로부터 랜덤하게 뽑은 9개의 숫자 (1 차원 array) **복원추출**

xr 의 형태를 바꾸어 (3,3) 행렬로 만들자

In [6]:
xr3 = xr.reshape(3,3) # 행렬일 경우 [[]]
xr3

array([[ 1,  6, 10],
       [ 3,  3,  4],
       [11,  6,  8]])

In [7]:
xr.shape
xr3.shape

(9,)

(3, 3)

In [11]:
xz= xr3.reshape((3,1,3)) # 3차원 [[[]]] 중간 1은 의미 없이 차원만 한 개 더 만들고 있음
xz

array([[[ 1,  6, 10]],

       [[ 3,  3,  4]],

       [[11,  6,  8]]])

In [12]:
xz.shape

(3, 1, 3)

In [13]:
xz.reshape((-1,3)) # 열만 3개로 바꾸고 싶은 경우 -1을 행에 넣으면 행은 알아서 정해준다

array([[ 1,  6, 10],
       [ 3,  3,  4],
       [11,  6,  8]])

In [14]:
xz

array([[[ 1,  6, 10]],

       [[ 3,  3,  4]],

       [[11,  6,  8]]])

In [16]:
xz.squeeze() # 의미없는 축(차원)을 없애줌 -> 짜준다.

array([[ 1,  6, 10],
       [ 3,  3,  4],
       [11,  6,  8]])

In [17]:
xz.squeeze().shape

(3, 3)

3x3 단위행렬을 만들어 보자 

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

3x3 형태의 0 행렬을 만들어 보자

In [19]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

행렬에 숫자를 더하면, 행렬의 모든 원소에 숫자가 더해진다 ( broadcasting )

In [21]:
np.zeros((3,3)) + 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.zeros((3,3)) + 1 + np.eye(3)

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [23]:
xr

array([ 1,  6, 10,  3,  3,  4, 11,  6,  8])

In [25]:
np.zeros((3,3))+1+np.eye(3)
xr.reshape(3,3)

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

array([[ 1,  6, 10],
       [ 3,  3,  4],
       [11,  6,  8]])

In [26]:
xm = np.zeros((3,3))+1+np.eye(3)+xr.reshape(3,3)
xm

array([[ 3.,  7., 11.],
       [ 4.,  5.,  5.],
       [12.,  7., 10.]])

In [27]:
xm

array([[ 3.,  7., 11.],
       [ 4.,  5.,  5.],
       [12.,  7., 10.]])

In [28]:
xm[0:2, 0:2] # 넘파이 -> [행,열]

array([[3., 7.],
       [4., 5.]])

In [31]:
xm[[0,1], [0,1]] # 0by0, 1by1 원소 추출 -> xm[0,0],xm[1,1]

array([3., 5.])

#### pandas

In [32]:
xm

array([[ 3.,  7., 11.],
       [ 4.,  5.,  5.],
       [12.,  7., 10.]])

In [33]:
xp = pd.DataFrame(xm)

In [34]:
xm.__class__

numpy.ndarray

In [35]:
xp.__class__

pandas.core.frame.DataFrame

In [36]:
xp

0    1     2
0   3.0  7.0  11.0
1   4.0  5.0   5.0
2  12.0  7.0  10.0

In [37]:
xm[0] # 넘파이 0 번째 행
xp[0] # 판다스 0 번째 열 Series

array([ 3.,  7., 11.])

0     3.0
1     4.0
2    12.0
Name: 0, dtype: float64

In [40]:
xm[0].__class__
xp[0].__class__

numpy.ndarray

pandas.core.series.Series

In [38]:
xp[[0]] # 판다스 0번째 열만 있는 데이터프레임

0
0   3.0
1   4.0
2  12.0

In [43]:
xp[[0]].__class__

pandas.core.frame.DataFrame

In [41]:
xp[0].shape

(3,)

In [42]:
xp[[0]].shape

(3, 1)

In [46]:
dict(xp) #판다스의 데이터프레임은 기본적으로 딕셔너리 클래스. column name을 key로 하고 series를 원소로 갖는 형태.

{0: 0     3.0
 1     4.0
 2    12.0
 Name: 0, dtype: float64,
 1: 0    7.0
 1    5.0
 2    7.0
 Name: 1, dtype: float64,
 2: 0    11.0
 1     5.0
 2    10.0
 Name: 2, dtype: float64}

In [47]:
xp
xp[:2]
xp[:2][[0,2]]

0    1     2
0   3.0  7.0  11.0
1   4.0  5.0   5.0
2  12.0  7.0  10.0

0    1     2
0  3.0  7.0  11.0
1  4.0  5.0   5.0

0     2
0  3.0  11.0
1  4.0   5.0

In [48]:
xp.iloc[[0,2],[0,2]]

0     2
0   3.0  11.0
2  12.0  10.0

In [49]:
xa = xp.copy()
xa.columns = list('abc')
xa

a    b     c
0   3.0  7.0  11.0
1   4.0  5.0   5.0
2  12.0  7.0  10.0

In [50]:
xp
xa

0    1     2
0   3.0  7.0  11.0
1   4.0  5.0   5.0
2  12.0  7.0  10.0

a    b     c
0   3.0  7.0  11.0
1   4.0  5.0   5.0
2  12.0  7.0  10.0

In [51]:
xp.iloc[0:2, 0:2]

0    1
0  3.0  7.0
1  4.0  5.0

In [55]:
xp.loc[0:2, 0:2] # 2를 포함

0    1     2
0   3.0  7.0  11.0
1   4.0  5.0   5.0
2  12.0  7.0  10.0

In [56]:
xa.loc[:, :'b'] # 'b'를 포함

a    b
0   3.0  7.0
1   4.0  5.0
2  12.0  7.0

In [58]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [59]:
x = pd.Series([1,2,3])
x.shape

(3,)

In [61]:
x = { u: u**2 for u in [1, 2, 3] }
x

{1: 1, 2: 4, 3: 9}

In [62]:
x = [ 1, 3, 5, 7, 8 ]; sum( x[:-2:2] )

6

In [63]:
x[:-2:2]

[1, 5]

In [65]:
[a+b for a,b in zip('abc','xyz') ]

['ax', 'by', 'cz']

In [67]:
zipp = zip('abc','xyz')

In [73]:
list(zipp)

[('a', 'x'), ('b', 'y'), ('c', 'z')]

In [71]:
enumerate([3,5,7,9])

In [72]:
list(enumerate([3, 5, 7, 9]))

[(0, 3), (1, 5), (2, 7), (3, 9)]

In [75]:
list(zip([3,5,7,9]))

[(3,), (5,), (7,), (9,)]

In [76]:
cbind([1,2,3,4],[3,5,7,9])

NameError: name 'cbind' is not defined

In [80]:
a=1 ; a++

SyntaxError: invalid syntax (4120415813.py, line 1)

In [85]:
xm = np.ones((3,3)) + np.array([[1],[2],[3]])
xm[2]

array([4., 4., 4.])

In [91]:
xm = np.arange(0,12).reshape((2,-1))
xm[[0]].shape

(1, 6)

In [92]:
x= range(0,4); x[-1]

3

In [93]:
'abc'+'def'

'abcdef'

In [94]:
5 % 3

2

In [96]:
xm = np.arange(0,6).reshape((3,1,2))
xm.squeeze().shape

(3, 2)