# R 과 Python 8주차 - 제2강

## Python 유용한 패키지들

다음 셀은, 이후의 셀에서, 각 셀에서 여러 개의 출력를
표시하도록 하는 옵션 설정 변경임

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

### numpy / pandas

In [2]:
import numpy as np
import pandas as pd

statsmodels 패키지: 다양한 통계모형들을 적용할 때 유용한 패키지

In [3]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

### numpy

In [4]:
xa = np.arange(1,12+1)
xr = np.random.choice(xa,9)
xa
xr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

array([ 3,  6,  1,  4,  9,  1,  2, 10,  7])

xa 는 1부터 12까지의 수열,

xr 은 xa 로부터 랜덤하게 뽑은 9개의 숫자 (1 차원 array)

xr 의 형태를 바꾸어 (3,3) 행렬로 만들자

In [5]:
xr3 = xr.reshape(3,3)
xr3

array([[ 3,  6,  1],
       [ 4,  9,  1],
       [ 2, 10,  7]])

In [6]:
xr.shape
xr3.shape

(9,)

(3, 3)

In [7]:
xz= xr3.reshape((3,1,3))
xz

array([[[ 3,  6,  1]],

       [[ 4,  9,  1]],

       [[ 2, 10,  7]]])

In [8]:
xz.shape

(3, 1, 3)

In [9]:
xz.reshape((-1,3))

array([[ 3,  6,  1],
       [ 4,  9,  1],
       [ 2, 10,  7]])

In [10]:
xz.squeeze()

array([[ 3,  6,  1],
       [ 4,  9,  1],
       [ 2, 10,  7]])

In [11]:
xz.squeeze().shape

(3, 3)

3x3 단위행렬을 만들어 보자 

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

3x3 형태의 0 행렬을 만들어 보자

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

행렬에 숫자를 더하면, 행렬의 모든 원소에 숫자가 더해진다 ( bradcasting )

In [14]:
np.zeros((3,3))+1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
np.zeros((3,3)) + 1 + np.eye(3)

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [16]:
xm = np.zeros((3,3))+1+np.eye(3)+xr.reshape(3,3)
xm

array([[ 5.,  7.,  2.],
       [ 5., 11.,  2.],
       [ 3., 11.,  9.]])

In [17]:
xm[0:2, 0:2]

array([[ 5.,  7.],
       [ 5., 11.]])

In [18]:
xm[[0,1], [0,1]]

array([ 5., 11.])

#### pandas

In [19]:
xp = pd.DataFrame(xm)

In [20]:
xp

0     1    2
0  5.0   7.0  2.0
1  5.0  11.0  2.0
2  3.0  11.0  9.0

In [21]:
xp[0]

0    5.0
1    5.0
2    3.0
Name: 0, dtype: float64

In [23]:
xp[[0]]

0
0  5.0
1  5.0
2  3.0

In [24]:
dict(xp)

{0: 0    5.0
 1    5.0
 2    3.0
 Name: 0, dtype: float64,
 1: 0     7.0
 1    11.0
 2    11.0
 Name: 1, dtype: float64,
 2: 0    2.0
 1    2.0
 2    9.0
 Name: 2, dtype: float64}

In [27]:
xp[:2]
xp[:2][[0,2]]

0     1    2
0  5.0   7.0  2.0
1  5.0  11.0  2.0

0    2
0  5.0  2.0
1  5.0  2.0

In [28]:
xp.iloc[[0,2],[0,2]]

0    2
0  5.0  2.0
2  3.0  9.0

#### pandas with mtcars

In [ ]:
mtcars = sm.datasets.get_rdataset('mtcars').data

In [ ]:
mtcars

열이름과 행이름을 알아보자

In [ ]:
mtcars.columns

In [ ]:
mtcars.index

일부 변수만을 뽑아 dx 데이터프레임을 만들자

In [ ]:
dx = mtcars[ ['gear', 'cyl', 'carb'] ]
dx

In [ ]:
dx[:3]

여러 개의 데이터프래임을 종으로 횡으로 연결하자.

pd.concat 을 사용할 때는, 연결하려는 데이터프레임을

리스트로 [ ] 묶어주고, 연결 방향을 axis 로 나타내야 한다.

In [ ]:
pd.concat( [ dx[:3], dx[3:6] ] , axis=0)

gear, cyl, carb 세 개의 변수값이 같은 경우의 개수를 세자

In [ ]:
dy = dx.groupby(['gear','cyl','carb'])[['carb']].count()
dy

개수를 세어서 얻게 된 결과 이름을 count 로 바꾸자

In [ ]:
dz = dy.rename(columns={'carb':'count'})
dz

인덱스 변수들을 일반 변수들로 바꾸어 다루기 쉽게 만들자

In [ ]:
dz.reset_index()

분할표의 형태를 ( gear cyl )을 인덱스로 하고, carb 값을 열로 하는 형태로 바꾸자

In [ ]:
dz.unstack()

NaN 을 0 으로 바꿔주자

In [ ]:
dz.unstack(fill_value=0)